### ISSUE TITLE
Increase/decrease volume?

### ISSUE THREAD

**Issue by coricidin12** [tmittet/sonos#4]
Is there a way to just increase or decrease the volume rather than setting it to a specific value? The node.js library has one.

**Comment by bopeterson** [comment]
The simple way would be to read volume, add the increase volume, and set new volume. I have an example at https://github.com/bopeterson/sonos-esp/blob/master/sonoscontrol/sonoscontrol.ino with my own sonos-esp library where I use a rotary encoder to increase/decrease volume instead of setting specific volume. See lines 103-112.

**Comment by coricidin12** [comment]
Thanks, that's exactly what I'm trying to do, volume control via rotary
encoder. I was thinking that it would be quicker and more responsive if
there was a way to bypass reading volume and adding the difference and just
do direct incrementation. How responsive is it in your application?

**Comment by bopeterson** [comment]
I find it responsive enough but  it could be made more responsive in two ways: 1) use interrupts to read encoder instead of polling 2) periodically read the volume from the sonos, say every 10 seconds, and use that value as input when you increase the value after the encoder is turned. 

I think 1) would lead to the most significant improvement, 2) should not be necessary.

**Comment by tmittet** [comment]
As bopeterson said, you can do:
byte value = getVolume(IP_Address);
value += 5;
setVolume(IP_Address, value);
